In [8]:
# example of For loop 
x= int(input("enter lines"))
for i in range(1,x+1):
    for j in range(1,i+1):
        print(j,end=" ")
    print(" ")
    


enter lines4
1  
1 2  
1 2 3  
1 2 3 4  


In [9]:
x= int(input("enter lines"))
for i in range(1,x+1):
    for j in range(x,i-1,-1):
        print(i,end=" ")
    print(" ")

enter lines4
1 1 1 1  
2 2 2  
3 3  
4  


In [10]:
import numpy as np
array1 = np.array([10.23,20,'a',30])
print(array1)

print(array1.ndim)
print(array1.shape)

['10.23' '20' 'a' '30']
1
(4,)


In [11]:
# sum the values of array
import numpy as np
array3 = np.array([[78,67,56], [76,56,47],[84,59,60],[67,72,54]])
print(array3.ndim)
print(array3.shape)
print(array3)
a=array3.shape
i=a[0]
j=a[1]
print("i",i, "j ", j)
sum=0
for c in range(i):
    for x in range(j):
        sum=sum+array3[c,x]
print(sum)

print(array3.max())

2
(4, 3)
[[78 67 56]
 [76 56 47]
 [84 59 60]
 [67 72 54]]
i 4 j  3
776
84


In [12]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [13]:
enum=8
print(enum)

8


In [14]:
s1,s2,s3,s4 = np.loadtxt('C:/Users/user/a1.txt', skiprows=1, delimiter=',',unpack=True,dtype = int)
print(s1)
print(s2)
print(s3)
print(s4)


OSError: C:/Users/user/a1.txt not found.

In [15]:
studentdata= np.loadtxt('C:/Users/user/a1.txt', skiprows=1, delimiter=',',unpack=True,dtype = int)
np.savetxt('C:/Users/user/a2.txt',studentdata, delimiter=',', fmt='%i')

OSError: C:/Users/user/a1.txt not found.

In [16]:
import pandas as pd
series1 = pd.Series([23000,34000,42000,30000,40000,50000])
print(series1)


0    23000
1    34000
2    42000
3    30000
4    40000
5    50000
dtype: int64


In [17]:
series1 = pd.Series([23000,34000,42000,30000,40000,50000],index=[100,200,300,400,500,600])
print(series1)
print(series1[::-3])

100    23000
200    34000
300    42000
400    30000
500    40000
600    50000
dtype: int64
600    50000
300    42000
dtype: int64


In [18]:
series1 = pd.Series([23000,34000,42000,30000,40000,50000], index=["jan","feb","march","april","may","june"]) #create a Series
print(series1)

jan      23000
feb      34000
march    42000
april    30000
may      40000
june     50000
dtype: int64


In [19]:
# Q1 CBSE file a) part 
import numpy as np
import pandas as pd
a1=np.array([12000,45000,67000,89000])
print(a1)
s1=pd.Series(a1, index=[0,4,8,10])
print(s1)

[12000 45000 67000 89000]
0     12000
4     45000
8     67000
10    89000
dtype: int32


In [20]:
# Q1 CBSE file b) part 
import numpy as np
import pandas as pd
a1={"jan": 23000,"feb": 35000,"march": 44000, "april": 55000, "may":67000}
s1=pd.Series(a1)
print(s1)
print(s1.values)
print(s1.size)
print(s1.count())
print(s1.head(3))
print(s1.tail(1))

jan      23000
feb      35000
march    44000
april    55000
may      67000
dtype: int64
[23000 35000 44000 55000 67000]
5
5
jan      23000
feb      35000
march    44000
dtype: int64
may    67000
dtype: int64


In [21]:
s1 = pd.Series(['NewDelhi','WashingtonDC', 'London', 'Paris'],index=['India', 'USA', 'UK', 'France'])
print(s1['India'])

NewDelhi


In [22]:
s1 = pd.Series(['NewDelhi', 'WashingtonDC', 'London',
'Paris'], index=['India', 'USA', 'UK', 'France'])
s1[1:3] #excludes the value at index position 3

USA    WashingtonDC
UK           London
dtype: object

In [23]:
s3= pd.Series([12,13,14,15], index=['apple', 'Guava', 'Papaya', 'BlueBerries'])
print(s3[3:0:-1])


BlueBerries    15
Papaya         14
Guava          13
dtype: int64


In [24]:
s1['USA' : 'France'] #If labelled indexes are used for slicing, then value at the end index label is also included in the output

USA       WashingtonDC
UK              London
France           Paris
dtype: object

In [25]:
print(seriesCapCntry[1:3])

print(seriesCapCntry[ : : -1]) # it will print reverse order


NameError: name 'seriesCapCntry' is not defined

In [26]:
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,20,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h','i', 'j'])
s2=pd.Series(np.arange(400,410,1),index = ['a', 'c', 'd', 'e', 'f','g','h','i', 'j','b'])
print(s1+s2)
# print(s1)
# s1[1:3] = 50 #use slicing to modify the values of series
# print(s1)
# s1['a': 'c']=250
print(s1.values)
print(s1.size)
print(s1.count())
print(s1.head(3))
print(s1.tail())

a    410
b    420
c    413
d    415
e    417
f    419
g    421
h    423
i    425
j    427
dtype: int32
[10 11 12 13 14 15 16 17 18 19]
10
10
a    10
b    11
c    12
dtype: int32
f    15
g    16
h    17
i    18
j    19
dtype: int32


In [27]:
import numpy as np
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [28]:
s2=pd.Series()
print(s2.empty)
print(s1.empty)

True
False


<ipython-input-28-f8d71a7228d8>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s2=pd.Series()


In [29]:
s1.name="C1"
s1.index.name="I1"
print(s1)

I1
a    10
b    11
c    12
d    13
e    14
f    15
g    16
h    17
i    18
j    19
Name: C1, dtype: int32


In [30]:
import pandas as pd
import numpy as np
series1=pd.Series(np.arange( 40,50, 1))
print(series1)
print(series1.head(6))
print(series1.count())
print(series1.tail())

0    40
1    41
2    42
3    43
4    44
5    45
6    46
7    47
8    48
9    49
dtype: int32
0    40
1    41
2    42
3    43
4    44
5    45
dtype: int32
10
5    45
6    46
7    47
8    48
9    49
dtype: int32


In [31]:
import pandas as pd
import numpy as np
a1=np.array([23,56,78,90])
s1=pd.Series(a1,index=['a','c','b','e'])
s2=pd.Series([201,403,234,323],index=["a","b","c","d"])
d1={"name":"Ramesh", "age": 56, "city":"Jaipur","state": "India"}
s3=pd.Series(d1)
print(s3)


name     Ramesh
age          56
city     Jaipur
state     India
dtype: object


In [32]:
s1 = pd.Series([1,2,3,4,5], index =['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])
# print(s1)
# print(s2)
print(s1/s2)
s1.div(s2, fill_value=1)


a   -0.10
b     NaN
c   -0.06
d     NaN
e    0.05
y     NaN
z     NaN
dtype: float64


a   -0.10
b    2.00
c   -0.06
d    4.00
e    0.05
y    0.05
z    0.10
dtype: float64

In [33]:
import pandas as pd
import numpy as np
d1 = pd.DataFrame()
print(d1)

Empty DataFrame
Columns: []
Index: []


In [34]:
# creating dataframe using array
import numpy as np
a1 = np.array([[101,'sheena',35,40000],[102,'Amit',33,14000],[103,'Tejas',44,15000]])
d1 = pd.DataFrame(a1, columns=[ 'Rollno', 'name', 'Age', 'Salary'])
print(d1)

  Rollno    name Age Salary
0    101  sheena  35  40000
1    102    Amit  33  14000
2    103   Tejas  44  15000


In [35]:
# creating dataframe using array
import numpy as np
a1 = np.array([101,'sheena',35,40000])
a2 = np.array([102,'Amit',33,14000])
a3 = np.array([103,'Tejas',44,15000])
d1 = pd.DataFrame([a1, a2,a3], columns=[ 'Rollno', 'name', 'Age', 'Salary'])
print(d1)

  Rollno    name Age Salary
0    101  sheena  35  40000
1    102    Amit  33  14000
2    103   Tejas  44  15000


In [36]:
# creating dataframe using list
import numpy as np
import pandas as pd
a1 = [101,'sheena',35,40000]
a2 = [102,'Amit',33,14000]
a3 = [103,'Tejas',44,15000]
d1 = pd.DataFrame([a1, a2,a3], columns=[ 'Rollno', 'name', 'Age', 'Salary'])
print(d1)

   Rollno    name  Age  Salary
0     101  sheena   35   40000
1     102    Amit   33   14000
2     103   Tejas   44   15000


In [37]:
# creating dataframe using dictionary inside list
import pandas as pd
import numpy as np
ld = [{'Tarun':70,'Babita':80,'Chetna':81},{'Tarun':56, 'Babita':79,'Chetna':61},{'Tarun':76, 'Babita':89,'Chetna':71}]
d1=pd.DataFrame(ld,index=['hindi','english','maths'])
print(d1)

         Tarun  Babita  Chetna
hindi       70      80      81
english     56      79      61
maths       76      89      71


In [38]:
# create a dataframe of the structure 
#     prodname    price   discount 
# 401  brush      158      45 
# 402  toothpaste  78      20
# 403  soap        74      15
# 1. add a column city ['jaipur','alwar','kota']
# 2. add a row  404  tea 345  54
# 3. drop a column discount
#4. Rename the index   401- pr401
#5. rename the columns 


In [39]:
import pandas as pd
ld = [{'prodname':'brush','price':158,'discount':45},{'prodname':'toothpaste','price':78,'discount':20},{'prodname':'soap','price':74,'discount':15}]
d1=pd.DataFrame(ld,index=['401','402','403'])
d1['city']=['jaipur','alwar','kota']  # city is added as column
d1.loc['404']=['tea',345,54,'surat']   # row is added
# d2=d1.drop(['discount'],axis=1)
d2=d1.drop(['404'],axis=0)
d3=d2.rename({'401':'pr401','402': 'pr402','403': 'pr403','404': 'pr404'},axis=0)
d4=d3.rename({'prodname':'prname','price': 'prodprice','city': 'prodcity'},axis=1)
print(d1)
print(d2)

       prodname  price  discount    city
401       brush    158        45  jaipur
402  toothpaste     78        20   alwar
403        soap     74        15    kota
404         tea    345        54   surat
       prodname  price  discount    city
401       brush    158        45  jaipur
402  toothpaste     78        20   alwar
403        soap     74        15    kota


In [40]:
d1= {'State': ['Assam', 'Delhi','Kerala'],'GArea': [78438, 1483, 38852] ,'VDF' : [2797, 6.72,1663]}
df1= pd.DataFrame(d1,index=[1,2,3])
print(df1)

    State  GArea      VDF
1   Assam  78438  2797.00
2   Delhi   1483     6.72
3  Kerala  38852  1663.00


In [41]:
s1 = pd.Series([1,2,3,4,5], index =['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])
df2=pd.DataFrame([s1,s2])
print(df2)

      a    b     c    d      e     z     y
0   1.0  2.0   3.0  4.0    5.0   NaN   NaN
1 -10.0  NaN -50.0  NaN  100.0  10.0  20.0


In [42]:
RS={ 'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
df3=pd.DataFrame(RS)
df3['Preeti']=[89,78,76]  # add column to dataframe
df3.loc['english']= [78,56,45,66,63,78]   # add row to dataframe
print(df3)

         Arnab  Ramit  Samridhi  Riya  Mallika  Preeti
Maths       90     92        89    81       94      89
Science     91     81        91    71       95      78
Hindi       97     96        88    67       99      76
english     78     56        45    66       63      78


In [43]:
print(df3.loc['Maths':'Hindi'])


         Arnab  Ramit  Samridhi  Riya  Mallika  Preeti
Maths       90     92        89    81       94      89
Science     91     81        91    71       95      78
Hindi       97     96        88    67       99      76


In [44]:
print(df3[0:2])

         Arnab  Ramit  Samridhi  Riya  Mallika  Preeti
Maths       90     92        89    81       94      89
Science     91     81        91    71       95      78


In [45]:
df3[: ] = 0
print(df3)

         Arnab  Ramit  Samridhi  Riya  Mallika  Preeti
Maths        0      0         0     0        0       0
Science      0      0         0     0        0       0
Hindi        0      0         0     0        0       0
english      0      0         0     0        0       0


In [46]:
RS={ 'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
df3=pd.DataFrame(RS)
print(df3)
df3.loc['Science']=0
df3['Ramit']=80
df3['Arnab']=95
print(df3)

         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       95     80        89    81       94
Science     95     80         0     0        0
Hindi       95     80        88    67       99


In [47]:
RS={ 'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
df3=pd.DataFrame(RS)
print(df3)
# df3 = df3.drop('Science',axis=0)
# print(df3)

         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99


In [48]:
df3= df3.drop(['Samridhi'], axis=1)
print(df3)

         Arnab  Ramit  Riya  Mallika
Maths       90     92    81       94
Science     91     81    71       95
Hindi       97     96    67       99


In [49]:
df3=df3.drop('Hindi', axis=0)
print(df3)

         Arnab  Ramit  Riya  Mallika
Maths       90     92    81       94
Science     91     81    71       95


In [50]:
RS={ 'Arnab': pd.Series([90, 91, 97,78],index=['Maths','Science','English','Hindi']),
'Ramit': pd.Series([92, 81, 96,89],index=['Maths','Science','English','Hindi']),
'Samridhi': pd.Series([89, 91, 88,90], index=['Maths','Science','English','Hindi']),
'Riya': pd.Series([81, 71, 67,76], index=['Maths','Science','English','Hindi']),
'Mallika': pd.Series([94, 95, 99,89],index=['Maths','Science','English','Hindi'])}
df3=pd.DataFrame(RS)
print(df3)
df3=df3.rename({'Maths':'Sub1','Science':'Sub2','English':'Sub3','Hindi':'Sub4'}, axis=0)  #index
print(df3)

         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
English     97     96        88    67       99
Hindi       78     89        90    76       89
      Arnab  Ramit  Samridhi  Riya  Mallika
Sub1     90     92        89    81       94
Sub2     91     81        91    71       95
Sub3     97     96        88    67       99
Sub4     78     89        90    76       89


In [51]:
df3=df3.rename({'Arnab':'Student1'},axis=1) # columns
print(df3)

      Student1  Ramit  Samridhi  Riya  Mallika
Sub1        90     92        89    81       94
Sub2        91     81        91    71       95
Sub3        97     96        88    67       99
Sub4        78     89        90    76       89


In [52]:
print(df3.loc['Sub2'])
print(df3.loc[:,'Ramit'])


Student1    91
Ramit       81
Samridhi    91
Riya        71
Mallika     95
Name: Sub2, dtype: int64
Sub1    92
Sub2    81
Sub3    96
Sub4    89
Name: Ramit, dtype: int64


In [53]:
RS={ 'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
df3=pd.DataFrame(RS)
print(df3)
print(df3.loc[df3['Science', 'Hindi']])


         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
         Arnab  Ramit  Samridhi  Riya  Mallika
Science     91     81        91    71       95
Hindi       97     96        88    67       99


In [54]:
print(df3.loc['Maths'] > 90)
print(df3.loc['Science'] > 80)
print(df3.loc[:,'Ramit'] >80 )
print(df3['Ramit'] >80 )

Arnab       False
Ramit        True
Samridhi    False
Riya        False
Mallika      True
Name: Maths, dtype: bool
Arnab        True
Ramit        True
Samridhi     True
Riya        False
Mallika      True
Name: Science, dtype: bool
Maths      True
Science    True
Hindi      True
Name: Ramit, dtype: bool
Maths      True
Science    True
Hindi      True
Name: Ramit, dtype: bool


In [55]:
import pandas as pd
df4=pd.DataFrame([10,20,30,40,50])
df4.loc[5]=60
print(df4)

    0
0  10
1  20
2  30
3  40
4  50
5  60


In [56]:
print(df3.loc['Maths': 'Science', 'Arnab':'Riya'])

         Arnab  Ramit  Samridhi  Riya
Maths       90     92        89    81
Science     91     81        91    71


In [57]:
print(df3)
print(df3.loc[[True, False, True]])
print(df3.loc[[True,True, False]])

         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99
       Arnab  Ramit  Samridhi  Riya  Mallika
Maths     90     92        89    81       94
Hindi     97     96        88    67       99
         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95


In [58]:
df1=pd.DataFrame([[1, 2, 3], [4, 5], [6]], columns=['C1', 'C2', 'C3'], index=['R1','R2', 'R3'])
df2=pd.DataFrame([[10, 20], [30], [40,50]], columns=['C2', 'C5'], index=['R4', 'R2','R5'])
print(df1)
print(df2)

    C1   C2   C3
R1   1  2.0  3.0
R2   4  5.0  NaN
R3   6  NaN  NaN
    C2    C5
R4  10  20.0
R2  30   NaN
R5  40  50.0


In [59]:
print(df1.append(df2, sort='True'))


     C1    C2   C3    C5
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0


In [60]:
print(df1.append(df2, ignore_index ='False'))

    C1    C2   C3    C5
0  1.0   2.0  3.0   NaN
1  4.0   5.0  NaN   NaN
2  6.0   NaN  NaN   NaN
3  NaN  10.0  NaN  20.0
4  NaN  30.0  NaN   NaN
5  NaN  40.0  NaN  50.0


In [61]:
import numpy as np
import pandas as pd
F1 = {'Assam' :pd.Series([78438, 2797,10192, 15116], index = ['GeoArea', 'VeryDense','ModeratelyDense', 'OpenForest']),'Kerala' :pd.Series([ 38852, 1663, 9407, 9251], index = ['GeoArea' ,'VeryDense',
'ModeratelyDense', 'OpenForest']),'Delhi' :pd.Series([1483, 6.72, 56.24,129.45], index = ['GeoArea', 'VeryDense',
'ModeratelyDense', 'OpenForest'])}
df4 = pd.DataFrame(F1)
print(df4)
print(df4.index)
print(df4.columns)
print(df4.dtypes)
print(df4.values)
print(df4.shape)
print(df4.size)
print(df4.T)

                 Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45
Index(['GeoArea', 'VeryDense', 'ModeratelyDense', 'OpenForest'], dtype='object')
Index(['Assam', 'Kerala', 'Delhi'], dtype='object')
Assam       int64
Kerala      int64
Delhi     float64
dtype: object
[[7.8438e+04 3.8852e+04 1.4830e+03]
 [2.7970e+03 1.6630e+03 6.7200e+00]
 [1.0192e+04 9.4070e+03 5.6240e+01]
 [1.5116e+04 9.2510e+03 1.2945e+02]]
(4, 3)
12
        GeoArea  VeryDense  ModeratelyDense  OpenForest
Assam   78438.0    2797.00         10192.00    15116.00
Kerala  38852.0    1663.00          9407.00     9251.00
Delhi    1483.0       6.72            56.24      129.45


In [62]:
print(df4.head(1))
print(df4.tail(1))
print(df4.empty)
df5=pd.DataFrame()
print(df5)
print(df5.empty)

         Assam  Kerala   Delhi
GeoArea  78438   38852  1483.0
            Assam  Kerala   Delhi
OpenForest  15116    9251  129.45
False
Empty DataFrame
Columns: []
Index: []
True


In [63]:
import pandas as pd
import numpy as np
m = pd.read_csv("C:/Users/suvig/citizen_data.csv",sep =",", header=0)
print(m)


    first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr   
1    Josephine    Darakjy          Chanay, Jeffrey A Esq   
2          Art     Venere            Chemel, James L Cpa   
3        Lenna   Paprocki         Feltz Printing Service   
4      Donette     Foller            Printing Dimensions   
..         ...        ...                            ...   
495    Brittni  Gillaspie                    Inner Label   
496    Raylene      Kampa                     Hermar Inc   
497        Flo   Bookamer   Simonton Howe & Schneider Pc   
498       Jani      Biddy  Warehouse Office & Paper Prod   
499   Chauncey     Motley     Affiliated With Travelodge   

                  address         city      county state    zip        phone1  \
0      6649 N Blue Gum St  New Orleans     Orleans    LA  70116  504-621-8927   
1     4 B Blue Ridge Blvd     Brighton  Livingston    MI  48116  810-292-9388   
2    8 W Cerritos Ave #54   Bridgepo

In [64]:
# Q6 from CBSE file part A
import pandas as pd  # importing file data into a dataframe
import numpy as np
m= pd.read_csv("C:/users/user/desktop/b.csv",sep =" ", names=['RNo','StudentName', 'English','Hindi'], header=0)
print(m)


FileNotFoundError: [Errno 2] No such file or directory: 'C:/users/user/desktop/b.csv'

In [65]:
# Q6 cbse file part B
import numpy as np
import pandas as pd
F1 = {'Assam' :pd.Series([78438, 2797,10192, 15116], index = ['GeoArea', 'VeryDense','ModeratelyDense', 'OpenForest']),'Kerala' :pd.Series([ 38852, 1663, 9407, 9251], index = ['GeoArea' ,'VeryDense',
'ModeratelyDense', 'OpenForest']),'Delhi' :pd.Series([1483, 6.72, 56.24,129.45], index = ['GeoArea', 'VeryDense',
'ModeratelyDense', 'OpenForest'])}
df4 = pd.DataFrame(F1)
print(df4)
df4.to_csv(path_or_buf="C:/Users/suvig/c.csv", sep=',')

                 Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45


In [66]:
RS={ 'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88], index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67], index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
df3=pd.DataFrame(RS)
print(df3)
df3.to_csv(path_or_buf="C:/users/user/desktop/d.csv", sep=',')

         Arnab  Ramit  Samridhi  Riya  Mallika
Maths       90     92        89    81       94
Science     91     81        91    71       95
Hindi       97     96        88    67       99


FileNotFoundError: [Errno 2] No such file or directory: 'C:/users/user/desktop/d.csv'

In [67]:

S1=pd.Series([14, 7, 9] ,index = range(1, 8, 3))
print(S1)

1    14
4     7
7     9
dtype: int64


In [68]:
S1=pd.Series()
print(pd.Series().empty)

True


<ipython-input-68-d09c82d6223e>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  S1=pd.Series()
<ipython-input-68-d09c82d6223e>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series().empty)
