In [2]:
# Series in Python Pandas

In [1]:
# creating empty Series
import pandas as pd
s = pd.Series()
print(s)

Series([], dtype: float64)


<ipython-input-1-a25eb6f6dc9c>:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [6]:
# creating series from scalar values with name 
import pandas as pd
s=pd.Series([35,40,48,52],name="Age")
print(s)

0    35
1    40
2    48
3    52
Name: Age, dtype: int64


In [12]:
# creating series from scalar values with user defined numeric index
import pandas as pd
s=pd.Series([35,40,48,52],index=[2,4,6,8],name="Age")
print(s)

2    35
4    40
6    48
8    52
Name: Age, dtype: int64


In [13]:
# creating series from scalar values with user defined labelled index
import pandas as pd
s=pd.Series([35,40,48,52],index=["Ramesh","Tarun","Shan","Utkarsh"],name="Age")
print(s)

Ramesh     35
Tarun      40
Shan       48
Utkarsh    52
Name: Age, dtype: int64


In [15]:
# creating series from dictionary
import pandas as pd
d1 = {"a":11,"b":12,"c":13,"d":14}
s = pd.Series(d1,name="UTmarks")
print(s)

a    11
b    12
c    13
d    14
Name: UTmarks, dtype: int64


In [24]:
# creating series from dictionary
import pandas as pd
d1 = {"a":11,"b":12,"c":13,"d":14}
s = pd.Series(d1,index=["a","b","c","d"],name="UTmarks")
print(s)

a    11
b    12
c    13
d    14
Name: UTmarks, dtype: int64


In [25]:
# creating series from dictionary
import pandas as pd
d1 = {"a":11,"b":12,"c":13,"d":14}
s = pd.Series(d1,index=["jan","feb","mar","apr"],name="UTmarks")
print(s)

jan   NaN
feb   NaN
mar   NaN
apr   NaN
Name: UTmarks, dtype: float64


In [34]:
# creating series from ndarray
import pandas as pd
import numpy as np
data = np.array([42500,35500,25000,51000,42000])
s = pd.Series(data)
print(s)


0    42500
1    35500
2    25000
3    51000
4    42000
dtype: int32


In [19]:
# creating series from ndarray
import pandas as pd
import numpy as np
data = np.array([42500,35500,25000,51000,42000])
s = pd.Series(data,index=['jan','feb','mar','apr','may'], name="expenditure")
print(s)

jan    42500
feb    35500
mar    25000
apr    51000
may    42000
Name: expenditure, dtype: int32


In [22]:
# creating series from ndarray using arange method
import pandas as pd
import numpy as np
data = np.arange(11000,20000,2000)
s = pd.Series(data)
print(s)

0    11000
1    13000
2    15000
3    17000
4    19000
dtype: int32


In [50]:
# accessing elements of a series
import pandas as pd
salary= pd.Series([25000,37000,28000,44000])
print(salary)

0    25000
1    37000
2    28000
3    44000
dtype: int64


In [47]:
# accessing elements of a series
import pandas as pd
salary= pd.Series([25000,37000,28000,44000])
print(salary)
print("Accessing 1st to 3rd element from the series")
print(salary[1:3])

0    25000
1    37000
2    28000
3    44000
dtype: int64
Accessing 1st to 3rd element from the series
1    37000
2    28000
dtype: int64


In [48]:
# accessing elements of a series
import pandas as pd
salary= pd.Series([25000,37000,28000,44000])
print(salary)
print("Accessing 1st to 3rd element from the series")
print(salary[[1,3]])

0    25000
1    37000
2    28000
3    44000
dtype: int64
Accessing 1st to 3rd element from the series
1    37000
3    44000
dtype: int64


In [56]:
# accessing elements of a series using labelled index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000])
print(salary)
print("Accessing 1st and 3rd element from the series")
print(salary[[1,3]])

0    25000
1    37000
2    28000
3    44000
dtype: int64
Accessing 1st and 3rd element from the series
1    37000
3    44000
dtype: int64


In [54]:
# accessing elements of a series using labelled index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("Accessing 2nd element from the series")
print(salary["feb"])

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
Accessing 1st to 3rd element from the series
37000


In [52]:
# accessing elements of a series using labelled index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("Accessing 1st to 3rd element from the series")
print(salary["jan": "mar"])

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
Accessing 1st to 3rd element from the series
jan    25000
feb    37000
mar    28000
dtype: int64


In [53]:
# accessing elements of a series using labelled index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("Accessing 1st and 3rd element from the series")
print(salary[["jan", "mar"]])

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
Accessing 1st to 3rd element from the series
jan    25000
mar    28000
dtype: int64


In [1]:
# displaying the series elements in reverse order
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("Accessing element from the series in reverse order")
print(salary[: : -1])

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
Accessing element from the series in reverse order
apr    44000
mar    28000
feb    37000
jan    25000
dtype: int64


In [2]:
# modifying the values of a series using positional index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("modifying the values of a series using positional index")
salary[1:3]=50000
print(salary)

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
modifying the values of a series 
jan    25000
feb    50000
mar    50000
apr    44000
dtype: int64


In [3]:
# modifying the values of a series using labelled index
import pandas as pd
salary= pd.Series([25000,37000,28000,44000],index=["jan","feb","mar","apr"])
print(salary)
print("modifying the values of a series using labelled index ")
salary["jan":"mar"]=60000
print(salary)

jan    25000
feb    37000
mar    28000
apr    44000
dtype: int64
modifying the values of a series 
jan    60000
feb    60000
mar    60000
apr    44000
dtype: int64


In [57]:
# modifying the index labels of a series
salary.index=['sun','mon','tue','wed']
print(salary)

sun    25000
mon    37000
tue    28000
wed    44000
dtype: int64


In [4]:
# Example of attribute of series
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
print(S1)

Arun     14
Tejas    16
Seema    17
Raj      15
dtype: int64


In [2]:
# Attributes of pandas # name 
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
S1.name= "Age"
print(S1)

Arun     14
Tejas    16
Seema    17
Raj      15
Name: Age, dtype: int64


In [3]:
# Attributes of pandas # index name 
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
S1.index.name= "Age"
print(S1)

Age
Arun     14
Tejas    16
Seema    17
Raj      15
dtype: int64


In [5]:
# Attributes of pandas # Value 
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
print(S1.values)

[14 16 17 15]


In [19]:
#Creating Series using scalar values
import pandas as pd
s = pd.Series(15,index=["Jack", "Jill", "John", "James"])
print(s)

Jack     5
Jill     5
John     5
James    5
dtype: int64


In [6]:
# Attributes of pandas # size 
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
print(S1.size)

4


In [22]:
#Creating Series using the index order
import pandas as pd
data = {"Jack":3, "Mill":2, "Brown":4, "Damie":1,}
s = pd.Series(data,index=["Jack", "Damie","Mill", "Brown"])
print(s)

Jack     3
Damie    1
Mill     2
Brown    4
dtype: int64


In [11]:
# Attributes of pandas # empty 
import pandas as pd
S1=pd.Series([14,16,17,15],index=['Arun','Tejas','Seema','Raj'])
S2=pd.Series()
print("Is S1 empty?", S1.empty)
print("Is S2 empty?",S2.empty)

Is S1 empty? False
Is S2 empty? True


<ipython-input-11-0d1d1489e04f>:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  S2=pd.Series()


In [5]:
import pandas as pd 
S1=pd.Series([350,120,65,789,250,79,190], index=['Tea','biscuit','soap','almonds','coffee','Register','Seeds'])
print(S1) # this will display the values of the series 

Tea         350
biscuit     120
soap         65
almonds     789
coffee      250
Register     79
Seeds       190
dtype: int64


In [6]:
print(S1.head(3)) # this will display first 3 records


Tea        350
biscuit    120
soap        65
dtype: int64


In [7]:
print(S1.head())  # this will display first 5 records by default

Tea        350
biscuit    120
soap        65
almonds    789
coffee     250
dtype: int64


In [8]:
import pandas as pd 
S1=pd.Series([350,120,65,789,250,79,190], index=['Tea','biscuit','soap','almonds','coffee','Register','Seeds'])
print(S1) # this will display the values of the series 

Tea         350
biscuit     120
soap         65
almonds     789
coffee      250
Register     79
Seeds       190
dtype: int64


In [10]:
print(S1.count())

7


In [11]:
import pandas as pd 
S1=pd.Series([350,120,65,789,250,79,190], index=['Tea','biscuit','soap','almonds','coffee','Register','Seeds'])
print(S1) # this will display the values of the series 

Tea         350
biscuit     120
soap         65
almonds     789
coffee      250
Register     79
Seeds       190
dtype: int64


In [12]:
print(S1.tail(2)) # this will display last 2 records

Register     79
Seeds       190
dtype: int64


In [13]:
print(S1.tail())  # this will display last 5 records by default

soap         65
almonds     789
coffee      250
Register     79
Seeds       190
dtype: int64


In [19]:
# Q1 CBSE file a) part 
import numpy as np
import pandas as pd
a1=np.array([12000,45000,67000,89000])
print(a1)
s1=pd.Series(a1, index=[0,4,8,10])
print(s1)

[12000 45000 67000 89000]
0     12000
4     45000
8     67000
10    89000
dtype: int32


In [20]:
# Q1 CBSE file b) part 
import numpy as np
import pandas as pd
a1={"jan": 23000,"feb": 35000,"march": 44000, "april": 55000, "may":67000}
s1=pd.Series(a1)
print(s1)
print(s1.values)
print(s1.size)
print(s1.count())
print(s1.head(3))
print(s1.tail(1))

jan      23000
feb      35000
march    44000
april    55000
may      67000
dtype: int64
[23000 35000 44000 55000 67000]
5
5
jan      23000
feb      35000
march    44000
dtype: int64
may    67000
dtype: int64


In [11]:
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,18,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h'])
s2=pd.Series(np.arange(400,408,1),index = ['a', 'm', 'd', 'e', 'f','g','h','i'])

In [15]:
print(s1)

a    10
b    11
c    12
d    13
e    14
f    15
g    16
h    17
dtype: int32


In [16]:
print(s2)

a    400
m    401
d    402
e    403
f    404
g    405
h    406
i    407
dtype: int32


In [17]:
s3=s1+s2
print(s3)

a    410.0
b      NaN
c      NaN
d    415.0
e    417.0
f    419.0
g    421.0
h    423.0
i      NaN
m      NaN
dtype: float64


In [19]:
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,18,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h'])
s2=pd.Series(np.arange(400,408,1),index = ['a', 'm', 'd', 'e', 'f','g','h','i'])
s3=s1.add(s2,fill_value=10)
print(s3)

a    410.0
b     21.0
c     22.0
d    415.0
e    417.0
f    419.0
g    421.0
h    423.0
i    417.0
m    411.0
dtype: float64


In [4]:
# performing subtraction with series 
print(s2-s1)

a    390.0
b      NaN
c      NaN
d    389.0
e    389.0
f    389.0
g    389.0
h    389.0
i      NaN
m      NaN
dtype: float64


In [6]:
# performing subtraction using sub() method
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,18,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h'])
s2=pd.Series(np.arange(400,408,1),index = ['a', 'm', 'd', 'e', 'f','g','h','i'])
s3=s2.sub(s1,fill_value=10)
print(s3)

a    390.0
b     -1.0
c     -2.0
d    389.0
e    389.0
f    389.0
g    389.0
h    389.0
i    397.0
m    391.0
dtype: float64


In [7]:
# performing multiplication  with series 
print(s2*s1)

a    4000.0
b       NaN
c       NaN
d    5226.0
e    5642.0
f    6060.0
g    6480.0
h    6902.0
i       NaN
m       NaN
dtype: float64


In [8]:
# performing multiplication using mul() method
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,18,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h'])
s2=pd.Series(np.arange(400,408,1),index = ['a', 'm', 'd', 'e', 'f','g','h','i'])
s3=s2.mul(s1,fill_value=10)
print(s3)

a    4000.0
b     110.0
c     120.0
d    5226.0
e    5642.0
f    6060.0
g    6480.0
h    6902.0
i    4070.0
m    4010.0
dtype: float64


In [9]:
# performing division  with series 
print(s2/s1)

a    40.000000
b          NaN
c          NaN
d    30.923077
e    28.785714
f    26.933333
g    25.312500
h    23.882353
i          NaN
m          NaN
dtype: float64


In [10]:
# performing division using div() method
import numpy as np
import pandas as pd
s1 = pd.Series(np.arange(10,18,1),index = ['a', 'b', 'c', 'd', 'e', 'f','g','h'])
s2=pd.Series(np.arange(400,408,1),index = ['a', 'm', 'd', 'e', 'f','g','h','i'])
s3=s2.div(s1,fill_value=10)
print(s3)

a    40.000000
b     0.909091
c     0.833333
d    30.923077
e    28.785714
f    26.933333
g    25.312500
h    23.882353
i    40.700000
m    40.100000
dtype: float64


In [39]:
import pandas as pd
ld = [{'prodname':'brush','price':158,'discount':45},{'prodname':'toothpaste','price':78,'discount':20},{'prodname':'soap','price':74,'discount':15}]
d1=pd.DataFrame(ld,index=['401','402','403'])
d1['city']=['jaipur','alwar','kota']  # city is added as column
d1.loc['404']=['tea',345,54,'surat']   # row is added
# d2=d1.drop(['discount'],axis=1)
d2=d1.drop(['404'],axis=0)
d3=d2.rename({'401':'pr401','402': 'pr402','403': 'pr403','404': 'pr404'},axis=0)
d4=d3.rename({'prodname':'prname','price': 'prodprice','city': 'prodcity'},axis=1)
print(d1)
print(d2)

       prodname  price  discount    city
401       brush    158        45  jaipur
402  toothpaste     78        20   alwar
403        soap     74        15    kota
404         tea    345        54   surat
       prodname  price  discount    city
401       brush    158        45  jaipur
402  toothpaste     78        20   alwar
403        soap     74        15    kota
